### ISSUE TITLE
where are the changelog or releasenotes?

### ISSUE THREAD

**Issue by jberends** [django-mptt/django-mptt#728] opened 2020-02-04 09:00 UTC
LS,

I have a hard time understanding what is going on in this package. I failed to see a releasenotes or changelog published. We use this package in the core of our application and I would really like to understand what are the changes from one minor version to another. As there are only 'tags' released since <0.10 it is very difficult to follow. (upgrade and hope).

Could you please report what is going on in each release and create a CHANGELOG.md of some sort between versions?

(I was not the first; see also #667)

**Comment by matthiask** [comment] 2020-02-04 16:06
This is a duplicate of https://github.com/django-mptt/django-mptt/issues/698

Also, the request for help still stands.

**Closed by matthiask** 2020-02-04 16:06 UTC
