### ISSUE TITLE
Admin list_filter breaking `cache_tree_children`

### ISSUE THREAD

**Issue by sjdines** [django-mptt/django-mptt#420] opened 2015-12-08 03:17 UTC
Consider I have 3 objects based off MPTT with a boolean field named `active`.

The first object is 0 level object with `active` set to False.
The second object is a 1 level object with the parent being the first object and with `active` set to True.
The third object is a 0 level object with `active` set to True.

On the admin list page we now add a `list_filter` on the field `active` (i.e. `list_filter = ['active', ]`) and filter the status of the objects to have `active` being True.

This will return a queryset containing the second and third object.

When reaching `cache_tree_children` the queryset then gets ordered by the following line:

```
queryset = queryset.order_by(tree_id_attr, left_attr)
```

The queryset will now be ordered to have the second object first in the queryset then the third object.

The function then iterates the queryset setting the `root_level` as the node level of the first object in the queryset (in this case 1) and proceeds to loop.

The second object now has a node level of zero and hits the following conditional:

```
if node_level < root_level:
    # ``queryset`` was a list or other iterable (unable to order),
    # and was provided in an order other than depth-first
    raise ValueError(
        _('Node %s not in depth-first order') % (type(queryset),)
     )
```

This will now compare the current `node_level` 0 and the `root_level` 1 and raise the `ValueError`.

From my perspective once the list has been filtered the tree structure does not make semantic sense and should probably be returned as a normal list view containing the filtered objects as a suggestion.

**Comment by craigds** [comment] 2015-12-10 02:02
Interesting. Note that this is newly merged behaviour; until now this just spewed a `DeprecationWarning`. What can we do here? Some thoughts.

1.
> once the list has been filtered the tree structure does not make semantic sense and should probably be returned as a normal list view

True. However I think I'd find that a bit confusing as a user, since it might not be obvious why my tree had become flat. There are other ways to filter things that would make sense with a tree (e.g. filtering by root nodes, or filtering nodes greater than a certain level)

2. Another way we could handle this would be to have `cache_tree_children` make two passes - once to make a map of all node IDs in the queryset, and a second pass to actually set `node.parent` and `parent._cached_children`. Then ordering would be a bit irrelevant ; if the parent of a node wasn't found it simply wouldn't be in the resultant queryset.

Option 2 would change the behaviour of cache_tree_children slightly - at present it returns a list of top-level (root) nodes, but this would make it potentially return nodes from other levels if the top-level nodes weren't in the original queryset. I think this would be great for the admin, but probably really confusing for some other uses (e.g. recursetree) so it might have to be an opt-in behaviour (e.g. with a keyword argument.)

**Comment by craigds** [comment] 2015-12-10 02:07
Actually.. I'm mistaken, this would have always thrown an error, it isn't newly merged behaviour. Though recent updates to `cache_tree_children` will make the error happen _slightly_ sooner.

**Comment by Wtower** [comment] 2015-12-11 10:39
To add details:

The full error is:

    InvalidTemplateLibrary at /el/
    Invalid template library specified. ImportError raised when trying to load 'mptt.templatetags.mptt_tags': cannot import name 'get_cached_trees'

The last working commit is https://github.com/django-mptt/django-mptt/commit/6c589a42da5513f4534f9ae1484afd79bc9f5f3d .

In case somebody lands here, to run mptt with Django 1.9:

    pip install git+https://github.com/django-mptt/django-mptt.git@fcc868dd238a59f2bed04871f62fae95ee09d243

**Comment by craigds** [comment] 2015-12-13 04:27
@Wtower that sounds like a different issue. I'm curious though, as that code is tested and the tests pass. Can you add more information in a new ticket?

**Comment by Wtower** [comment] 2015-12-13 09:54
I see. This morning that I tried to reproduce it on my home pc I haven't been able to, I got to go to my work PC tomorrow where I also have kept a full stack trace. It seems that it might have to do with some other package as well, I will look into it. What I get is a totally different error that I investigate and I will come back to when ready.

**Comment by Wtower** [comment] 2015-12-13 10:36
Ok. The error that I have described previously happened only with the packaged 0.7.4 version and Django 1.9, but it is ok with latest master, so I will skip this. Unless you are interested for more details.

**Comment by craigds** [comment] 2015-12-13 21:16
no worries, thanks :)

**Comment by gjedeer** [comment] 2016-06-23 09:20
@Wtower thank you very much, it was a life saver! After upgrading to Django 1.9 not only that exception was thrown in the admin part of our app, but menus in the front-end part were completely distorted (some menu items placed under different parent items, some missing - complete mess). Downgrading django-mptt to fcc868dd238a59f2bed04871f62fae95ee09d243 made it work.

I'm worried about further updates, though. What's the recommended upgrade procedure when one hits this error? Do I just need to rebuild all the trees with fcc868dd238a59f2bed04871f62fae95ee09d243 and I'm safe to upgrade django-mptt?

**Comment by Wtower** [comment] 2016-06-23 09:29
Welcome friend. Now that you brought this up I think that any version v0.8.0+ should actually work.. At least I haven't had that issue with any later releases, so this would probably need further investigation.

**Comment by Aramgutang** [comment] 2016-08-26 09:11
@craigds it's not one of the 2 fixes you suggested, but this approach handles filtered querysets better, even though nodes will look like top-level trees in the displayed tree when they're not.

Ugh, as I write this, I'm realising this doesn't deal with the case of search results that are in the same tree, but a higher-level result precedes a lower-level one. I might need to go away and think of a better fix.

**Comment by Aramgutang** [comment] 2016-08-26 10:48
OK, have come up with a better implementation.

For the master branch, the change to utils.cache_tree_children uses a keyword argument, per suggestion 2(b), so anything using it directly will not see any change in behaviour, so recursetree would not be affected.

The cache_tree_children template filter, however uses the keyword argument after checking if the thing passed as a queryset is a queryset and has filters applied. That last part is an attempt at maintaining previous behaviour in as many cases as possible, so that if people pass incorrectly ordered lists or querysets (that aren't filtered), the ValueError is still thrown.

The 0.7.x branch also checks for a filtered queryset for the same reasons, in the same place as the ordering check via order_by.

Now, my reasoning as to why this should be merged, even though it changes behaviour slightly:

The way this function works is already quite confusing and takes liberties with how the cached representation of the tree (as accessed via _cached_children and parent_attr) is constructed for filtered querysets. Consider this tree:

```
T1A - T1B - T1C
    - T1D
    - T1E - T1F
T2A - T2B
```

If we had a search filter that only included T1A, T1D, T1F, and T2B, the cached version of the tree that the function would return would be:

```
T1A - T1D - T1F
    - T2B
```

This needs to be fixed eventually, by replacing the `node_level < root_level` check by something proper like `root.tree_id == node.tree_id and root.lft < node.lft and root.rght > node.rght`. However, I wanted to limit the scope of my fix and change as little behaviour as possible beyond fixing the 500 errors thrown in the django admin, so I left that as an open issue.

The reason I mention this issue is that "confusing" people by making nodes without included ancestors appear as top-level nodes is not nearly as big of a concern in light of that.

If the filtered queryset's first node isn't on a deeper level than any of the others, the chances of which happening we can't guess, only then a 500 is thrown. This basically means that any search term in the django admin has a chance of resulting in a 500 error. It's a big enough problem that people have attempted to work around it in strange ways such as here: https://github.com/django-fluent/django-fluent-pages/commit/a33059164f53152b96452598ddfea00724a338e7

My argument is that avoiding random 500 errors in the admin and potentially confusing some users of that templatetag (where they would get a ValueError otherwise) is a better option than the current implementation (which already returns confusing results if the ordering happens to _appear_ correct) or workarounds like the one I linked above (which results in incomplete search results by filtering out non-top-level results).

**Comment by Aramgutang** [comment] 2016-08-29 07:47
Test failures on 0.7.x branch now fixed; there was a very weird issue with Python 3.2 there.

**Closed** 2022-05-19 11:03 UTC
