### ISSUE TITLE
NOT NULL constraint failed: model.level in Data Migration

### ISSUE THREAD

**Issue by ycanales** [django-mptt/django-mptt#350] opened 2014-12-19 15:30 UTC
I'm using Data Migrations in Django 1.7 to populate the database.
And I get the following error when creating a object whose model is a MPTTModel subclass (Category model):

    #migration code
    [...]
    Category.objects.create(name='Clothes')
    [...]
    # log when executing the migration
    [...]
    django.db.utils.IntegrityError: NOT NULL constraint failed: products_category.level

I infer this is due to the lack of signal emitting in migrations, and I guess it's in a signal that django-mptt creates the proper attributes automatically (like `level`).
I tried [this approach](http://stackoverflow.com/questions/26542617/how-can-i-send-signals-from-within-django-migrations) to manually send the signals without luck.

Thanks in advance for your help.

**Comment by craigds** [comment] 2015-02-06 22:28
django-mptt doesn't get called at all during migrations, no custom code does. only django's base code gets called, so you have to either migrate stuff yourself, or run `from yourapp.models import YourModel ; YourModel.objects.rebuild()` at the end of the migration.

dupe of #195 - django-mptt could support migrations better.

**Closed by craigds** 2015-02-06 22:28 UTC
