### ISSUE TITLE
Don't publish 'tests' as a separate package..

### ISSUE THREAD

**Issue by iljamaas** [django-mptt/django-mptt#472] opened 2016-06-03 08:22 UTC
The distributed  django-mptt packages contain a '**tests**' directory which, when installed, is a top-level site-package, which can easily conflict with other package (doing the same thing ... )

I think the tests should either be NOT included in the packages, OR, be put inside the django-mptt package to prevent conflicts.

**Comment by matthiask** [comment] 2016-06-03 09:23
Thanks for the report! This is a duplicate of #453.

**Closed by matthiask** 2016-06-03 09:23 UTC
