### ISSUE TITLE
With Django-1.10  error

### ISSUE THREAD

**Issue by shtalinberg** [django-mptt/django-mptt#501] opened 2016-08-21 19:47 UTC
After update Django to 1.10  I see this error :
```
./manage.py runserver
Unhandled exception in thread started by <function wrapper at 0x7f0afd514398>
Traceback (most recent call last):
  File ".venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File ".venv/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File ".venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File ".venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File ".venv/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File ".venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File ".venv/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File ".venv/local/lib/python2.7/site-packages/mptt/models.py", line 385, in <module>
    class MPTTModel(six.with_metaclass(MPTTModelBase, models.Model)):
  File ".venv/local/lib/python2.7/site-packages/django/utils/six.py", line 808, in __new__
    return meta(name, bases, d)
  File ".venv/local/lib/python2.7/site-packages/mptt/models.py", line 263, in __new__
    cls = super_new(meta, class_name, bases, class_dict)
  File ".venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 157, in __new__
    new_class.add_to_class(obj_name, obj)
  File ".venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File ".venv/local/lib/python2.7/site-packages/mptt/managers.py", line 82, in contribute_to_class
    super(TreeManager, self).contribute_to_class(model, name)
  File ".venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 120, in contribute_to_class
    setattr(model, name, ManagerDescriptor(self))
AttributeError: can't set attribute
```
version mptt == 0.8.5
with Django 1.9.9 work fine.

**Comment by ad-m** [comment] 2016-08-21 21:25
Duplicate of #488, #469, #493. Close, please.

**Comment by matthiask** [comment] 2016-08-22 05:25
Thanks for the report. Closing as duplicate.

**Closed by matthiask** 2016-08-22 05:25 UTC
