### ISSUE TITLE
Django 1.10 incompatibility

### ISSUE THREAD

**Issue by karolyi** [django-mptt/django-mptt#488] opened 2016-08-02 14:31 UTC
Hey,

I just upgraded Django to 1.10, and here's the error:

```python
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "xxxx/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "xxxx/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "xxxx/venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "xxxx/venv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "xxxx/venv/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "xxxx/webmaster_stats/visualizer/faq/models.py", line 7, in <module>
    from mptt.models import MPTTModel, TreeForeignKey, TreeOneToOneField
  File "xxxx/venv/lib/python3.5/site-packages/mptt/models.py", line 385, in <module>
    class MPTTModel(six.with_metaclass(MPTTModelBase, models.Model)):
  File "xxxx/venv/lib/python3.5/site-packages/django/utils/six.py", line 808, in __new__
    return meta(name, bases, d)
  File "xxxx/venv/lib/python3.5/site-packages/mptt/models.py", line 263, in __new__
    cls = super_new(meta, class_name, bases, class_dict)
  File "xxxx/venv/lib/python3.5/site-packages/django/db/models/base.py", line 157, in __new__
    new_class.add_to_class(obj_name, obj)
  File "xxxx/venv/lib/python3.5/site-packages/django/db/models/base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "xxxx/venv/lib/python3.5/site-packages/mptt/managers.py", line 82, in contribute_to_class
    super(TreeManager, self).contribute_to_class(model, name)
  File "xxxx/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 120, in contribute_to_class
    setattr(model, name, ManagerDescriptor(self))
AttributeError: can't set attribute
```

**Comment by patrys** [comment] 2016-08-02 16:00
This is a duplicate of #469

**Comment by matthiask** [comment] 2016-08-03 05:51
Thank you! Yes, that issue is already known.

**Closed by matthiask** 2016-08-03 05:51 UTC
