### ISSUE TITLE
Regression in 0.7.0: MPTTModelBase.register() no longer supports using explicitly-declared left/right/tree_id/level fields

### ISSUE THREAD

**Issue by pjdelport** [django-mptt/django-mptt#376] opened 2015-05-04 17:39 UTC
I have a codebase that runs fine django-mptt 0.6.1 and earlier, but crashes with 0.7.0 and later, with "django.db.utils.OperationalError: duplicate column name" errors.

I tracked the regression down to changeset 3ebca5b (part of issue #356), which changed the field contribution code to no longer check whether the dynamic field being added already exists on the target model.

The old code reads:

```python
for key in ('left_attr', 'right_attr', 'tree_id_attr', 'level_attr'):
    field_name = getattr(cls._mptt_meta, key)
    try:
        cls._meta.get_field(field_name)
    except models.FieldDoesNotExist:
        field = models.PositiveIntegerField(db_index=True, editable=False)
        field.contribute_to_class(cls, field_name)
```

The new code is identical, except for omitting the `get_field` check:

```python
for key in ('left_attr', 'right_attr', 'tree_id_attr', 'level_attr'):
    field_name = getattr(cls._mptt_meta, key)
    field = models.PositiveIntegerField(db_index=True, editable=False)
    field.contribute_to_class(cls, field_name)
```

According to [the documentation](https://github.com/django-mptt/django-mptt/blob/0.7.2/docs/models.rst#model-options), the old behavior is correct and intended.

Is there any downside to restoring the `get_field()` check to what it was before? The only caution I can find is that in Django 1.8, `get_field()` finds more fields than before ([1.8 migration notes](https://docs.djangoproject.com/en/1.8/ref/models/meta/#migrating-old-meta-api)), but as far as I can see this shouldn't really affect MPTT's prior usage of it.

**Comment by craigds** [comment] 2015-05-05 19:54
Good question. I guess I made that change thinking it was useless code, but obviously not.

The problem is that `get_field` just doesn't work any more at this stage of model loading - it only works once models have all been loaded.

I don't know why the django devs didn't put that in the migration notes. AFAICT there's no way to get a field instance before `AppCache.ready` now.

Upstream ticket was https://code.djangoproject.com/ticket/24231 but it was closed 'wontfix'.

**Comment by craigds** [comment] 2015-05-05 20:41
@pjdelport if you can confirm this fixes the bug for you, I'll make a new point release for fixing this regression.

**Closed** 2015-05-05 20:41 UTC

**Comment by pjdelport** [comment] 2015-05-05 20:50
That seems like it should fix it! I'll test in the morning, to confirm.

**Comment by pjdelport** [comment] 2015-05-06 12:20
@craigds: This fix works for me.

A point release would be awesome, thanks!
