### ISSUE TITLE
Using abstract model mixin breaks foreign keys to MPTT models?

### ISSUE THREAD

**Issue by egasimus** [django-mptt/django-mptt#287] opened 2014-01-17 17:44 UTC
(SO question: http://stackoverflow.com/questions/21191650/why-do-model-mixins-break-django-mptt-foreign-keys)

I'm modifying a third-party Django app based on django-mptt. I'm trying to refactor one monstrously big model into a base class and a set of mixins. All seemed well, however...

    class ModelMixin([see below]):
        class Meta:
            abstract = True
    
    class BaseModel(ModelMixin, MPTTModel):
        class Meta:
            abstract = False

 1. If `ModelMixin` inherits from `object`, South doesn't see any fields declared in the mixin.
 2. If `ModelMixin` inherits from `mptt.models.MPTTModel`, the extra fields that django-mptt adds to MPTT-aware models get added twice; which `django-mptt` doesn't like, even though the mixin is abstract.
 3. Most interestingly, if `ModelMixin` inherits from `django.db.models.Model`, I get this bloody weird error when I try to introduce a foreign key to that model:

Traceback:

    File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py"
        line 900, in set_field_name
    self.field_name = self.field_name or self.to._meta.pk.name
    AttributeError: 'NoneType' object has no attribute 'name'

**Comment by simone-divitel** [comment] 2016-06-09 12:52
Just my two cents: this issue seems to appear only when using pyhton 2.7 and not in 3.4.

**Comment by matthiask** [comment] 2016-06-14 20:27
I have the suspicion that this problem disappeared because of changes in Django, being unable to reproduce the failure ~20 months later. (https://travis-ci.org/matthiask/django-mptt/builds/137599120)

Closing, please reopen if you disagree.

**Closed by matthiask** 2016-06-14 20:27 UTC
Labels: Needsinfo
